# Generated by Django 4.0.3 on 2022-03-16 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='id_project',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
