# Generated by Django 4.0.3 on 2022-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_userdetail_id_project_userdetail_project_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminupload1',
            name='filecontent1',
        ),
        migrations.AddField(
            model_name='adminupload1',
            name='filecontent',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='adminupload2',
            name='filecontent2',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/certifate'),
        ),
    ]
