# Generated by Django 4.0.3 on 2022-03-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_adminupload1_filecontent1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminupload1',
            new_name='Adminupload',
        ),
    ]
