# Generated by Django 4.0.3 on 2022-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_adminupload1_adminupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id_certi', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='media/documents/certificate')),
            ],
        ),
        migrations.DeleteModel(
            name='Adminupload2',
        ),
    ]
