# Generated by Django 4.0.3 on 2022-03-22 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_certificateupload_delete_adminupload2'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminupload',
            name='announcement',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
